# Generated by Django 3.1.5 on 2021-03-12 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RenameModel(
            old_name='Trending_tags',
            new_name='Trending_tag',
        ),
    ]
