# Generated by Django 3.1.5 on 2021-03-13 11:35

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210312_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='media',
            field=models.ImageField(default='images', upload_to=home.models.Content.user_directory_path),
            preserve_default=False,
        ),
    ]
