# Generated by Django 3.1.5 on 2021-03-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_content_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='owner_info',
            field=models.TextField(default='unavailable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('DEL', 'Deleted'), ('COM', 'Completed'), ('PEN', 'Pending')], default='DEL', max_length=3),
        ),
    ]
